//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAdvisor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialAdvisor.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Requête vide ?.
        /// </summary>
        public static string EmptyQueryString {
            get {
                return ResourceManager.GetString("EmptyQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide.
        /// </summary>
        public static string HelpString {
            get {
                return ResourceManager.GetString("HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salut.
        /// </summary>
        public static string HiString {
            get {
                return ResourceManager.GetString("HiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        public static string LanguageString {
            get {
                return ResourceManager.GetString("LanguageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vouliez-vous dire :.
        /// </summary>
        public static string MeanString {
            get {
                return ResourceManager.GetString("MeanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas plus de requêtes disponibles pour ce mois-ci, Désolé.
        /// </summary>
        public static string NoMoreQueriesString {
            get {
                return ResourceManager.GetString("NoMoreQueriesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé, je ne comprends pas, s’il vous plaît dites « Aide » pour voir des exemples.
        /// </summary>
        public static string UnknownQuery {
            get {
                return ResourceManager.GetString("UnknownQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je peux faire des conversions ou calculs entre monnaies..
        /// </summary>
        public static string UsageFirstLine {
            get {
                return ResourceManager.GetString("UsageFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soyez indulgent, je suis en cours d’élaboration  ;-).
        /// </summary>
        public static string UsageFourthLine {
            get {
                return ResourceManager.GetString("UsageFourthLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à comme « convertir 100 dollars en yens &quot; ou « ajouter 100 dollars et 10 yens en euros ».
        /// </summary>
        public static string UsageSecondLine {
            get {
                return ResourceManager.GetString("UsageSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je peux obtenir des prix d&apos;actions comme « quel est le prix de Microsoft ? ».
        /// </summary>
        public static string UsageThirdLine {
            get {
                return ResourceManager.GetString("UsageThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue {0}, je suis Bob, votre conseiller financier..
        /// </summary>
        public static string WelcomeStringFirstLine {
            get {
                return ResourceManager.GetString("WelcomeStringFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dire « Aide » pour savoir ce que je peux faire pour vous.
        /// </summary>
        public static string WelcomeStringSecondLine {
            get {
                return ResourceManager.GetString("WelcomeStringSecondLine", resourceCulture);
            }
        }
    }
}
