//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAdvisor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialAdvisor.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Goodbye, have a nice day.
        /// </summary>
        public static string ByeString {
            get {
                return ResourceManager.GetString("ByeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Query empty?.
        /// </summary>
        public static string EmptyQueryString {
            get {
                return ResourceManager.GetString("EmptyQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string HelpString {
            get {
                return ResourceManager.GetString("HelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello.
        /// </summary>
        public static string HiString {
            get {
                return ResourceManager.GetString("HiString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a possible language.
        /// </summary>
        public static string LanguageUnaivalable {
            get {
                return ResourceManager.GetString("LanguageUnaivalable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Did you mean:.
        /// </summary>
        public static string MeanString {
            get {
                return ResourceManager.GetString("MeanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now, I speak.
        /// </summary>
        public static string NewLanguageString {
            get {
                return ResourceManager.GetString("NewLanguageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No more queries available for this month, I&apos;m sorry.
        /// </summary>
        public static string NoMoreQueriesString {
            get {
                return ResourceManager.GetString("NoMoreQueriesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speak.
        /// </summary>
        public static string SpeakString {
            get {
                return ResourceManager.GetString("SpeakString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, I don&apos;t understand, please say &quot;help&quot; to see examples.
        /// </summary>
        public static string UnknownQuery {
            get {
                return ResourceManager.GetString("UnknownQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tell me: &quot;speak ...&quot; to change the language.
        /// </summary>
        public static string UsageFifthLine {
            get {
                return ResourceManager.GetString("UsageFifthLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can do conversions or calculations between currencies..
        /// </summary>
        public static string UsageFirstLine {
            get {
                return ResourceManager.GetString("UsageFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be forgiving, I am being developed ;-).
        /// </summary>
        public static string UsageFourthLine {
            get {
                return ResourceManager.GetString("UsageFourthLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à as &quot;convert 100 dollars into yen&quot;or &quot;100 usd + 10 gbp in euros&quot;.
        /// </summary>
        public static string UsageSecondLine {
            get {
                return ResourceManager.GetString("UsageSecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can get the price of actions such as &quot;what is the price of Microsoft?&quot;.
        /// </summary>
        public static string UsageThirdLine {
            get {
                return ResourceManager.GetString("UsageThirdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I am available in these languages: .
        /// </summary>
        public static string WelcomeLanguageAvailable {
            get {
                return ResourceManager.GetString("WelcomeLanguageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome {0}, I&apos;m Bob, your financial advisor..
        /// </summary>
        public static string WelcomeStringFirstLine {
            get {
                return ResourceManager.GetString("WelcomeStringFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Say &quot;help&quot; to see what I can do for you..
        /// </summary>
        public static string WelcomeStringSecondLine {
            get {
                return ResourceManager.GetString("WelcomeStringSecondLine", resourceCulture);
            }
        }
    }
}
